import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { streamObject } from "ai";
import { ollama } from "ollama-ai-provider";
import { z } from "zod";
import type { Route } from "./+types/analyze-paragraph";
const ERROR_POSITION = z.object({
	errorText: z.string().describe("The text you found to be incorrect."),
});

export const ERROR_UNION = z.discriminatedUnion("type", [
	z.object({
		type: z.literal("GRAMMAR_ERROR"),
		reasoning: z.string(),
		position: ERROR_POSITION,
	}),
	z.object({
		type: z.literal("AI_DETECTED"),
		reasoning: z.string(),
		position: ERROR_POSITION,
		confidence: z
			.number()
			.describe(
				"How much are you confident that this text is AI generated in a percent.",
			),
	}),
	z.object({
		type: z.literal("STYLE_IMPROVEMENT"),
		reasoning: z.string(),
		improvement: z.string(),
		position: ERROR_POSITION,
	}),
]);

export const ANALYSIS_SCHEMA = z.object({
	errors: z.array(ERROR_UNION),
});

const SYSTEM_PROMPT = `You are a professional text analyzer specializing in identifying and correcting grammar errors, improving sentence structure, and detecting potential AI-generated text. Your task is to evaluate one paragraph at a time based on these criteria:
1. **Grammar and Syntax**: Identify and correct any grammatical, spelling, or punctuation errors.
2. **Stylistic Improvements**: Highlight poorly worded sentences or awkward phrasing and suggest more effective alternatives.
3. **AI-Generated Content Detection**: Analyze the paragraph for patterns or language styles that may indicate AI authorship and provide an explanation for your assessment.
Provide your feedback in a structured format with actionable insights and corrections.
`;

const getMessagePrompt = (text: string) => {
	return `Analyze the following paragraph based on the following criteria:
1. **Grammar and Syntax**: Identify and correct errors.
2. **Stylistic Improvements**: Highlight awkward or poorly worded sentences and suggest improvements.
3. **AI-Generated Content Detection**: Assess whether the text may have been generated by AI and explain your reasoning.

Here is the paragraph:
${text}
`;
};

const google = createGoogleGenerativeAI({
	apiKey: process.env.VERTEX_KEY,
});

export async function action({ request }: Route.ActionArgs) {
	const jsonBody = await request.json();
	const paragraph = jsonBody.text;
	if (!paragraph) return Error("No text");
	console.log(SYSTEM_PROMPT, getMessagePrompt(paragraph));
	const object = streamObject({
		model:
			process.env.AI_PROVIDER === "ollama"
				? ollama("llama3.1", {})
				: google("gemini-1.5-flash-8b", {
						structuredOutputs: false,
					}),
		schemaName: "Analysis",
		schemaDescription: "Analysis results",
		schema: ANALYSIS_SCHEMA,
		prompt: getMessagePrompt(paragraph.toString()),
		system: SYSTEM_PROMPT,
	});
	return new Response(object.textStream, {
		headers: {
			"Content-Type": "text/event-stream",
		},
	});
}
